phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/ | apt-key add -
      - node --version
      - npm config set registry https://registry.npmjs.org/
      - npm config set @empresateste:registry https://npm.platforms.engineering
      - npm config set //npm.platforms.engineering/:_authToken $NPM_AUTH_TOKEN
      - npm install
      - npm --version
